// The app icon files are generated by build-icons.mjs, from one geometry.
//
// Two ways they go wrong without this: someone edits a PNG by hand (or the
// geometry, without re-running the script) and the files drift apart, so the home
// screen, the install icon and the tab disagree; or an HTML document or the
// manifest names an icon file that is not there, which a browser reports nowhere
// and an operator sees only as a blank or generic icon.

import { strict as assert } from "node:assert";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import { inflateSync } from "node:zlib";

import { JSDOM } from "jsdom";

// @ts-expect-error -- a plain .mjs script with no type declarations
const { buildIcons } = await import("./build-icons.mjs");

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = path.join(ROOT, "public");

/**
 * A PNG's header and pixels, decompressed. The compressed bytes are not compared:
 * zlib builds differ between Node versions and compress the same pixels to
 * different bytes. Anything after IEND fails, so nothing can ride along unseen.
 */
function decodePng(file: Buffer, name: string): { header: Buffer; pixels: Buffer } {
  let at = 8;
  let header: Buffer | null = null;
  const idat: Buffer[] = [];
  for (;;) {
    const len = file.readUInt32BE(at);
    const type = file.toString("ascii", at + 4, at + 8);
    const data = file.subarray(at + 8, at + 8 + len);
    at += 12 + len;
    if (type === "IHDR") header = data;
    else if (type === "IDAT") idat.push(data);
    else if (type === "IEND") break;
  }
  assert.equal(at, file.length, `public/${name} has bytes after its IEND chunk`);
  assert.ok(header, `public/${name} has no IHDR chunk`);
  return { header, pixels: inflateSync(Buffer.concat(idat)) };
}

test("every committed icon is exactly what build-icons.mjs produces", () => {
  const built = buildIcons() as Record<string, string | Buffer>;
  assert.deepEqual(
    Object.keys(built).sort(),
    ["apple-touch-icon.png", "favicon.svg", "icon-192.png", "icon-512.png", "icon-maskable-512.png"],
  );
  for (const [name, data] of Object.entries(built)) {
    const committed = readFileSync(path.join(PUBLIC, name));
    const drawn = Buffer.from(data);
    const message = `public/${name} differs from what scripts/build-icons.mjs draws. Run \`npm run icons\` and commit the result.`;
    if (name.endsWith(".png")) {
      const a = decodePng(committed, name);
      const b = decodePng(drawn, name);
      assert.ok(a.header.equals(b.header) && a.pixels.equals(b.pixels), message);
    } else {
      assert.ok(committed.equals(drawn), message);
    }
  }
});

test("the PNG icons are the sizes their names and the manifest say", () => {
  const size = (name: string) => {
    const png = readFileSync(path.join(PUBLIC, name));
    return [png.readUInt32BE(16), png.readUInt32BE(20)];
  };
  assert.deepEqual(size("apple-touch-icon.png"), [180, 180]);
  assert.deepEqual(size("icon-192.png"), [192, 192]);
  assert.deepEqual(size("icon-512.png"), [512, 512]);
  assert.deepEqual(size("icon-maskable-512.png"), [512, 512]);
});

test("every icon the HTML documents and the manifest name exists in public/", () => {
  const named: string[] = [];
  for (const doc of ["index.html", "app.html"]) {
    // Parsed, so a commented-out link is not an element and is not counted.
    const parsed = new JSDOM(readFileSync(path.join(ROOT, doc), "utf8")).window.document;
    const tags = [...parsed.querySelectorAll('link[rel="icon"], link[rel="apple-touch-icon"]')];
    assert.equal(tags.length, 2, `${doc} should declare one rel="icon" and one rel="apple-touch-icon"`);
    for (const tag of tags) named.push(tag.getAttribute("href")?.replace(/^\//, "") ?? `(no href in ${doc})`);
  }
  const manifest = JSON.parse(readFileSync(path.join(PUBLIC, "manifest.webmanifest"), "utf8")) as {
    icons: { src: string; purpose: string }[];
  };
  for (const icon of manifest.icons) named.push(icon.src.replace(/^\//, ""));
  assert.ok(manifest.icons.some((i) => i.purpose === "maskable"), "the manifest has no maskable icon");
  for (const name of named) assert.ok(existsSync(path.join(PUBLIC, name)), `public/${name} is named but missing`);
});
