// Kiosk devices — the machines that SHOW displays, as opposed to the displays
// themselves.
//
// An Output is "Left Mic Display": a name, a view, a slug, a permanent id that
// QR codes point at. A kiosk device is the Raspberry Pi screwed to the wall
// behind it. They are deliberately separate: swap the dead Pi for a new one and
// the output — with everything pointing at it — is untouched.
//
// Two halves, and only one is stored. See kiosk-devices-store.ts.

/**
 * What size a screen is actually running at.
 *
 * TWO numbers, because they answer different questions and neither is a lie:
 *
 *  • `w`/`h` are CSS pixels as the browser sees them, with `dpr` alongside. This
 *    is what a LAYOUT is measured in, so it is the number that answers "will my
 *    view fit" — a HiDPI panel reports 1920x1080 at dpr 2, not 3840x2160.
 *  • `mode` is the display mode the machine is actually driving, read from DRM on
 *    Linux. It is the answer to "what is this TV doing", and it is the one that
 *    exposes a TV overscanning or negotiating an odd EDID mode, which the browser
 *    number cannot see.
 */
export interface ScreenSize {
  w: number;
  h: number;
  dpr?: number;
  /** e.g. "1920x1080". Linux agents only — absent elsewhere. */
  mode?: string;
}

/**
 * What one device is, when it is one output of a Mac running the output helper.
 *
 * The helper announces ONE device per output (a built-in display or a DeckLink
 * SDI port), each with its own id, and all of them share the Mac's `macs` and
 * `hostname`. This is what tells them apart for a person: Screens groups them
 * under the Mac and names each one by this.
 *
 * Untrusted off the wire — see `decodeOutput` in kiosk-discovery.ts.
 */
export interface DeviceOutput {
  kind: DeviceOutputKind;
  /** What the operator reads on the row, e.g. "SDI 1 · Card A". */
  name: string;
  /** Which physical port, e.g. "SDI 1". */
  port: string;
  /** The video modes this port reported, e.g. "1080p59.94". A DeckLink port
   *  only; a display has none worth choosing. */
  modes?: string[];
}

export const DEVICE_OUTPUT_KINDS = ["decklink", "display"] as const;
export type DeviceOutputKind = (typeof DEVICE_OUTPUT_KINDS)[number];

/** A device the operator has claimed. STORED — this is their work. */
export interface BoundDevice {
  /** Generated by the installer, presented by the agent. Permanent. */
  id: string;
  /** Issued on claim; presented on every enrolment afterwards. Without it a
   *  device id is self-asserted and anything on the LAN could ask to be served a
   *  claimed display's content. */
  token: string;
  /** The Output this device shows. */
  outputId: string;
  /** The operator's name for the physical box. Defaults to its hostname. */
  label?: string;
  /** Hints for re-identifying the same hardware. NEVER used to bind — Wi-Fi MACs
   *  randomise per network and a NIC swap changes them, so a match suggests and a
   *  person confirms. */
  macs: string[];
  hostname?: string;
  os?: string;
  ip?: string;
  /** What it is running at, as last reported. */
  screen?: ScreenSize;
  /** Present when this is one output of a Mac running the output helper. Kept on
   *  the stored record, as the hardware facts above are, so a bound output still
   *  says which port it is after the probe that carried it has gone quiet. */
  output?: DeviceOutput;
  /** Epoch ms. Persisted so Devices can say "last seen Tuesday" after a server
   *  restart rather than "never". */
  lastSeen?: number;
}

/**
 * A device currently shouting on the network. NOT STORED.
 *
 * It exists only while it is actually probing: in memory, TTL'd, gone on
 * restart. That is why powering a Pi off before pairing it makes it vanish from
 * every server's list — there was never anything to clean up.
 */
export interface SeenDevice {
  id: string;
  macs: string[];
  hostname?: string;
  os?: string;
  ip: string;
  firstSeen: number;
  lastSeen: number;
  /** The server this device says owns it, if any. */
  boundTo?: string;
  screen?: ScreenSize;
  /** See {@link DeviceOutput}. Absent for every device that is not a helper output. */
  output?: DeviceOutput;
  /** The device cannot reach the server that owns it. Only then does another
   *  server show it at all, and only behind an explicit force-claim. */
  unreachable?: boolean;
}

/** What a device broadcasts. Untrusted: this arrives on a broadcast port. */
export interface DiscoveryProbe {
  id: string;
  macs: string[];
  hostname?: string;
  os?: string;
  boundTo?: string;
  unreachable?: boolean;
  /** The display mode the machine is driving, when it can tell us. */
  mode?: string;
  /** Set by the Mac output helper, once per output. See {@link DeviceOutput}. */
  output?: DeviceOutput;
}

/** What a server answers with. */
export interface DiscoveryReply {
  /** Stable per install, so a device can tell two servers apart. */
  serverId: string;
  /** Human name, shown in Devices so a binding is attributable. */
  name: string;
  /** Where to load the display from. */
  url: string;
}

/** The default discovery port. Adjustable — AV gear is fond of odd UDP ports,
 *  and a collision should be a settings change rather than a rebuild. */
export const DEFAULT_DISCOVERY_PORT = 8789;
