// Kiosk devices — the machines that SHOW displays, as opposed to the displays
// themselves.
//
// An Output is "Left Mic Display": a name, a view, a slug, a permanent id that
// QR codes point at. A kiosk device is the Raspberry Pi screwed to the wall
// behind it. They are deliberately separate: swap the dead Pi for a new one and
// the output — with everything pointing at it — is untouched.
//
// Two halves, and only one is stored. See kiosk-devices-store.ts.

/** A device the operator has claimed. STORED — this is their work. */
export interface BoundDevice {
  /** Generated by the installer, presented by the agent. Permanent. */
  id: string;
  /** Issued on claim; presented on every enrolment afterwards. Without it a
   *  device id is self-asserted and anything on the LAN could ask to be served a
   *  claimed display's content. */
  token: string;
  /** The Output this device shows. */
  outputId: string;
  /** The operator's name for the physical box. Defaults to its hostname. */
  label?: string;
  /** Hints for re-identifying the same hardware. NEVER used to bind — Wi-Fi MACs
   *  randomise per network and a NIC swap changes them, so a match suggests and a
   *  person confirms. */
  macs: string[];
  hostname?: string;
  os?: string;
  ip?: string;
  /** Epoch ms. Persisted so Devices can say "last seen Tuesday" after a server
   *  restart rather than "never". */
  lastSeen?: number;
}

/**
 * A device currently shouting on the network. NOT STORED.
 *
 * It exists only while it is actually probing: in memory, TTL'd, gone on
 * restart. That is why powering a Pi off before pairing it makes it vanish from
 * every server's list — there was never anything to clean up.
 */
export interface SeenDevice {
  id: string;
  macs: string[];
  hostname?: string;
  os?: string;
  ip: string;
  firstSeen: number;
  lastSeen: number;
  /** The server this device says owns it, if any. */
  boundTo?: string;
  /** The secret this device presented when it last loaded /enroll. Kept in
   *  memory only and never broadcast — it arrives over unicast HTTP, not in the
   *  probe, so it is not shouted at the whole LAN. */
  secret?: string;
  /** The device cannot reach the server that owns it. Only then does another
   *  server show it at all, and only behind an explicit force-claim. */
  unreachable?: boolean;
}

/** What a device broadcasts. Untrusted: this arrives on a broadcast port. */
export interface DiscoveryProbe {
  id: string;
  macs: string[];
  hostname?: string;
  os?: string;
  boundTo?: string;
  unreachable?: boolean;
}

/** What a server answers with. */
export interface DiscoveryReply {
  /** Stable per install, so a device can tell two servers apart. */
  serverId: string;
  /** Human name, shown in Devices so a binding is attributable. */
  name: string;
  /** Where to load the display from. */
  url: string;
}

/** The default discovery port. Adjustable — AV gear is fond of odd UDP ports,
 *  and a collision should be a settings change rather than a rebuild. */
export const DEFAULT_DISCOVERY_PORT = 8789;
