// The exact set of layout object types, for tests only.
//
// Five guards across main and renderer each pinned this set with a bare count
// (`assert.equal(types.length, 62)`), and every one of them lived on the same
// line two branches would touch when each added a type — a guaranteed merge
// conflict, and a count that cannot tell an add plus a remove from no change.
//
// One list here, sorted, one entry per line, replaces all five. Two branches
// adding different types touch different lines and merge cleanly; the rare
// same-line collision resolves as "keep both". Each guard asserts the
// registry's keys, sorted, equal this list exactly.
export const LAYOUT_OBJECT_TYPES = [
  "action-button",
  "baptism-timer",
  "brand-logo",
  "charger-battery",
  "checklist",
  "clock",
  "container",
  "countdown-timer",
  "cue-button",
  "current-service-item",
  "current-slide-notes",
  "current-slide-text",
  "home-live-status",
  "home-next-service",
  "home-pvp",
  "home-pvp-now",
  "home-readiness",
  "home-recent-services",
  "home-recording",
  "home-recording-obs",
  "home-recording-reaper",
  "home-scores",
  "home-screens",
  "home-spl",
  "home-streaming",
  "home-streaming-resi",
  "home-streaming-youtube",
  "image",
  "integration-status",
  "live-controls",
  "ndi-video",
  "next-service-item",
  "next-slide-text",
  "notes",
  "obs-status",
  "osc-button",
  "people-counter",
  "people-graph",
  "people-panel",
  "plan-attachment",
  "pp-timer",
  "pvp-layers",
  "pvp-now",
  "reaper-status",
  "record-status",
  "rosstalk-button",
  "scores",
  "screen-embed",
  "section-chip",
  "service-order",
  "service-pacing",
  "shape",
  "slide-progress",
  "slide-thumbnail",
  "slots-grid",
  "spl-meter",
  "stream-status",
  "text",
  "transcript-strip",
  "view-embed",
  "wireless-channel",
  "wireless-summary",
] as const;
